# Generated by Django 4.2 on 2026-03-09 10:14

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название серии')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL')),
                ('series_type', models.CharField(choices=[('monolithic', 'Монолитная'), ('block', 'Блочная')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Серия блоков',
                'verbose_name_plural': 'Серии блоков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media/images/%Y/%m/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиабиблиотека',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CharacteristicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('wall_thickness', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Толщина стены (мм)')),
                ('thermal_conductivity', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Теплопроводность')),
                ('sound_insulation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Звукоизоляция (дБ)')),
                ('concrete_consumption', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Расход бетона (м³/м²)')),
                ('weight_per_sqm', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вес 1 м² стены (кг)')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_groups', to='products.blockseries', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Группа характеристик',
                'verbose_name_plural': 'Группы характеристик',
                'ordering': ['series', 'wall_thickness'],
                'unique_together': {('series', 'wall_thickness')},
            },
        ),
        migrations.AddField(
            model_name='blockseries',
            name='additional_media',
            field=models.ManyToManyField(blank=True, related_name='series_media', to='products.medialibrary', verbose_name='Дополнительные медиа'),
        ),
        migrations.AddField(
            model_name='blockseries',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_main_image', to='products.medialibrary', verbose_name='Главное фото'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('corner', 'Угловой'), ('inline', 'Рядный'), ('inline_extended', 'Рядный удлиненный'), ('other', 'Другой')], max_length=20, verbose_name='Тип блока')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Длина (мм)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина (мм)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Высота (мм)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вес блока (кг)')),
                ('pallet_quantity', models.PositiveIntegerField(verbose_name='Количество на поддоне')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('additional_media', models.ManyToManyField(blank=True, related_name='block_media', to='products.medialibrary', verbose_name='Дополнительные медиа')),
                ('characteristic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='products.characteristicgroup', verbose_name='Группа характеристик')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_main_image', to='products.medialibrary', verbose_name='Главное фото')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='products.blockseries', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['series', 'block_type'],
                'unique_together': {('series', 'block_type', 'characteristic_group')},
            },
        ),
    ]
