# Generated by Django 4.2 on 2026-03-09 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medialibrary',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиабиблиотека'},
        ),
        migrations.RenameField(
            model_name='medialibrary',
            old_name='video_url',
            new_name='video_link',
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_media', to='products.block', verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt'])], verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='media/drawings/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['dwg', 'dxf', 'cdw', 'step', 'stp', 'iges', 'igs'])], verbose_name='Чертеж'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video_file', 'Видеофайл'), ('video_link', 'Ссылка на видео'), ('document', 'Документ'), ('drawing', 'Чертеж'), ('other', 'Другое')], default='image', max_length=20, verbose_name='Тип медиа'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='other_file',
            field=models.FileField(blank=True, null=True, upload_to='media/other/%Y/%m/', verbose_name='Другой файл'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_media', to='products.blockseries', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])], verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='blockseries',
            name='main_image',
            field=models.ForeignKey(blank=True, limit_choices_to={'media_type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_main_image', to='products.medialibrary', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Для изображений', max_length=200, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg'])], verbose_name='Изображение'),
        ),
        migrations.AddIndex(
            model_name='medialibrary',
            index=models.Index(fields=['media_type'], name='products_me_media_t_9f950e_idx'),
        ),
        migrations.AddIndex(
            model_name='medialibrary',
            index=models.Index(fields=['block'], name='products_me_block_i_3dbc77_idx'),
        ),
        migrations.AddIndex(
            model_name='medialibrary',
            index=models.Index(fields=['series'], name='products_me_series__6d3067_idx'),
        ),
    ]
