# Generated by Django 4.2 on 2026-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_medialibrary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockseries',
            name='order',
            field=models.SmallIntegerField(default=10, verbose_name='Порядок'),
        ),
    ]
