# Generated by Django 4.2 on 2024-02-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя посетителя')),
                ('phone', models.CharField(max_length=10, verbose_name='телефон')),
                ('connect_time', models.DateTimeField(auto_now_add=True, verbose_name='время обращения')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip адрес')),
            ],
        ),
    ]
