# Generated by Django 4.2 on 2024-02-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip адрес'),
        ),
    ]
