# Generated by Django 4.2 on 2024-02-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_options_alter_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='crm_error',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='crm_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='дополнения'),
        ),
    ]
