# Generated by Django 4.2 on 2024-02-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_crm_error_feedback_crm_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='телефон'),
        ),
    ]
