# Generated by Django 4.2 on 2026-01-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('одноэтажный', 'Одноэтажный дом'), ('двухэтажный', 'Двухэтажный дом'), ('с мансардой', 'Дом с мансардой'), ('полутороэтажный', 'Полутораэтажный дом'), ('гараж', 'Гараж'), ('производственное помещение', 'Производственное помещение'), ('офис', 'Офисное здание'), ('не определился', 'Пока не определился')], max_length=50)),
                ('land_status', models.CharField(choices=[('есть участок', 'Есть участок'), ('в процессе покупки', 'В процессе покупки'), ('планирую покупать', 'Планирую покупать'), ('нужна помощь', 'Нужна помощь в подборе')], max_length=50)),
                ('project_status', models.CharField(choices=[('готовый проект', 'Готовый проект'), ('есть эскиз', 'Есть эскиз'), ('есть наброски', 'Есть эскизы и наброски'), ('заказать проект', 'Хочу заказать проект'), ('нужна консультация', 'Нужна консультация')], max_length=50)),
                ('timeline', models.CharField(choices=[('как можно скорее', 'Как можно скорее'), ('хочу консультацию', 'Хочу сначала проконсультироваться'), ('в течении года', 'В течение года'), ('3-6 месяцев', 'В течение 3-6 месяцев'), ('в этом месяце', 'В течение этого месяца')], max_length=50)),
                ('payment_method', models.CharField(choices=[('собственные средства', 'Собственные средства'), ('ипотека', 'Ипотека')], max_length=50)),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comments', models.TextField(blank=True)),
                ('data_agreement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя посетителя')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='дополнения')),
                ('crm_status', models.BooleanField(default=False)),
                ('crm_error', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('connect_time', models.DateTimeField(auto_now_add=True, verbose_name='время обращения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip адрес')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
