# Generated by Django 4.2 on 2026-03-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrequest',
            name='square',
            field=models.CharField(choices=[('less50', 'до 50 м.кв.'), ('from50to100', 'от 50 м.кв. до 100 м.кв.'), ('from100to150', 'от 100 м.кв. до 150 м.кв.'), ('more150', 'более 150 м.кв.')], default='less50', max_length=50),
        ),
    ]
