# Generated by Django 4.2 on 2026-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_calculationrequest_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationrequest',
            name='house_type',
            field=models.CharField(choices=[('одноэтажный', 'Одноэтажный дом'), ('двухэтажный', 'Двухэтажный дом'), ('с мансардой', 'Дом с мансардой'), ('полутороэтажный', 'Полутораэтажный дом'), ('гараж', 'Гараж'), ('производственное помещение', 'Производственное помещение'), ('офис', 'Офисное здание'), ('не определился', 'Пока не определился'), ('по проекту', 'Согласно выбранного проекта')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calculationrequest',
            name='payment_method',
            field=models.CharField(choices=[('собственные средства', 'Собственные средства'), ('ипотека', 'Ипотека'), ('эскроу', 'Эскроу')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calculationrequest',
            name='project_status',
            field=models.CharField(choices=[('готовый проект', 'Готовый проект'), ('есть эскиз', 'Есть эскиз'), ('есть наброски', 'Есть эскизы и наброски'), ('заказать проект', 'Хочу заказать проект'), ('нужна консультация', 'Нужна консультация'), ('выбрал ваш проект', 'Выбрал ваш проект на сайте')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calculationrequest',
            name='square',
            field=models.CharField(choices=[('less50', 'до 50 м.кв.'), ('from50to100', 'от 50 м.кв. до 100 м.кв.'), ('from100to150', 'от 100 м.кв. до 150 м.кв.'), ('more150', 'более 150 м.кв.'), ('project', 'Согласно выбранного проекта')], default='less50', max_length=50),
        ),
    ]
