# Generated by Django 4.2 on 2026-04-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_calculationrequest_house_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationrequest',
            name='contact_method',
            field=models.CharField(choices=[('max', 'MAX'), ('telegram', 'Telegram'), ('email', 'Email'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], max_length=50),
        ),
    ]
