# Generated by Django 4.2 on 2026-03-15 10:34

import apps.portfolio.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название района')),
                ('center_latitude', models.DecimalField(decimal_places=8, help_text='Например: 55.7558', max_digits=10, verbose_name='Широта центра')),
                ('center_longitude', models.DecimalField(decimal_places=8, help_text='Например: 37.6176', max_digits=11, verbose_name='Долгота центра')),
                ('boundary_geojson', models.JSONField(blank=True, help_text='GeoJSON объект с границами района', null=True, verbose_name='Границы района GeoJSON')),
                ('houses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество домов')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('built_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год постройки')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь (м²)')),
                ('floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество этажей')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена в рублях', max_digits=12, null=True, verbose_name='Цена')),
                ('status', models.CharField(choices=[('built', 'Построен'), ('in_progress', 'Строится'), ('planning', 'В планах')], default='built', max_length=20, verbose_name='Статус')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Например: {"material": "кирпич", "parking": true}', verbose_name='Дополнительные характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='portfolio.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=20, verbose_name='Тип медиа')),
                ('file', models.FileField(max_length=500, upload_to=apps.portfolio.models.house_media_path, verbose_name='Файл')),
                ('video_url', models.URLField(blank=True, help_text='Для видео можно указать внешнюю ссылку', verbose_name='Ссылка на видео')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Медиафайл дома',
                'verbose_name_plural': 'Медиафайлы домов',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерировано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('response_text', models.TextField(blank=True, verbose_name='Ответ компании')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portfolio.house', verbose_name='Дом')),
                ('photos', models.ManyToManyField(blank=True, help_text='Можно прикрепить фото из медиатеки дома', to='portfolio.housemedia', verbose_name='Фото к отзыву')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='portfolio_d_name_82b030_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['center_latitude', 'center_longitude'], name='portfolio_d_center__d9c989_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['house', '-created_at'], name='portfolio_r_house_i_2a398f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'is_published'], name='portfolio_r_rating_317987_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['district', 'status'], name='portfolio_h_distric_656965_idx'),
        ),
    ]
