# Generated by Django 4.2 on 2026-04-07 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.AlterField(
            model_name='house',
            name='built_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2050)], verbose_name='Год постройки'),
        ),
    ]
