# Generated by Django 4.2 on 2026-04-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_house_address_remove_house_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['order'], 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='floors',
        ),
        migrations.AddField(
            model_name='house',
            name='order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='house',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='Фото дома'),
        ),
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default=2, max_length=250, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Например: {"material": ["ThermoBlock 300", ], "garage": true, "teracce": True, "heating": "Гибридное"}', verbose_name='Дополнительные характеристики'),
        ),
    ]
