# Generated by Django 4.2 on 2026-04-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('referer', models.URLField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для QR-кода', unique=True)),
                ('name', models.CharField(help_text='Название ссылки (для админки)', max_length=200)),
                ('target_url', models.URLField(help_text='Конечный URL для перехода', max_length=2000)),
                ('qr_code', models.ImageField(blank=True, help_text='Загрузите готовый QR-код (PNG, JPEG, SVG)', null=True, upload_to='qr_codes/')),
                ('qr_code_url', models.URLField(blank=True, help_text='Или укажите URL внешнего QR-кода')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['slug'], name='qr_tracker__slug_2625c9_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedlink',
            index=models.Index(fields=['is_active'], name='qr_tracker__is_acti_7d9a94_idx'),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='qr_tracker.trackedlink'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['link', 'clicked_at'], name='qr_tracker__link_id_57ffa2_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['session_key'], name='qr_tracker__session_63881e_idx'),
        ),
    ]
