# Generated by Django 4.2 on 2026-04-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedlink',
            name='qr_code_url',
        ),
    ]
