# Generated by Django 4.2 on 2026-01-22 18:04

import apps.instructions.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True, verbose_name='название инструкции')),
                ('description', models.TextField(verbose_name='краткое описание инструкции')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Инструкцию',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=35, verbose_name='название этапа')),
                ('description', models.TextField(verbose_name='краткое описание этапа')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructions.instractions', verbose_name='инструкция')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'unique_together': {('instruction', 'page')},
            },
        ),
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=25, verbose_name='название рекомендации')),
                ('description', models.TextField(verbose_name='рекомендация')),
                ('type_media', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('url', 'Ссылка'), ('file', 'Файл')], default='image', max_length=6, verbose_name='тип медиа к рекомендации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instractions', verbose_name='изображение')),
                ('file', models.FileField(blank=True, null=True, upload_to='instractions', verbose_name='файл')),
                ('video', models.FileField(blank=True, null=True, upload_to='img_instractions', validators=[apps.instructions.validators.validate_is_video], verbose_name='видео')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на ресурс')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructions.stage', verbose_name='этап инструкции')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
