# Generated by Django 4.2 on 2024-02-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Артикул', max_length=25, unique=True, verbose_name='Название продукта')),
                ('subtitle', models.CharField(max_length=55, verbose_name='Подзаголовок продукта')),
                ('length', models.IntegerField(help_text='(мм.)', verbose_name='Длинна блока')),
                ('width', models.IntegerField(help_text='(мм.)', verbose_name='Ширина блока')),
                ('height', models.IntegerField(help_text='(мм.)', verbose_name='Высота блока')),
                ('block_weight', models.IntegerField(help_text='(кг.)', verbose_name='Вес блока')),
                ('blocks_in_paddon', models.IntegerField(help_text='(шт.)', verbose_name='Блоков в паддоне')),
                ('soundproofing', models.DecimalField(decimal_places=2, help_text='(Дб)', max_digits=4, verbose_name='Звукоизоляция')),
                ('concrete', models.DecimalField(decimal_places=3, help_text='(м.куб./м.кв.)', max_digits=4, verbose_name='расход бетона')),
                ('block_consumption', models.DecimalField(decimal_places=2, help_text='(шт./м.кв.)', max_digits=4, verbose_name='Расход блоков')),
                ('images', models.ImageField(upload_to='img_products', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='MediaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_products', verbose_name='Изображение')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название параметра')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Значение')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='продукт')),
            ],
        ),
    ]
