# Generated by Django 4.2 on 2026-03-05 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('article', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Артикул')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь, м²')),
                ('rooms_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество комнат')),
                ('bathrooms_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество санузлов')),
                ('floors_count', models.DecimalField(blank=True, decimal_places=1, help_text='1 - одноэтажный, 1.5 - полутораэтажный, 2 - двухэтажный и т.д.', max_digits=3, null=True, verbose_name='Количество этажей')),
                ('bedrooms_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество спален')),
                ('garage', models.BooleanField(default=False, verbose_name='Гараж')),
                ('terrace', models.BooleanField(default=False, verbose_name='Терраса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='Главное изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярное')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект строения',
                'verbose_name_plural': 'Проекты строений',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип строения',
                'verbose_name_plural': 'Типы строений',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoofType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип крыши',
                'verbose_name_plural': 'Типы крыш',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/projectgallery/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='constructs.product', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проектов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='constructs.producttype', verbose_name='Тип строения'),
        ),
        migrations.AddField(
            model_name='product',
            name='roof_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='constructs.rooftype', verbose_name='Тип крыши'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='constructs__slug_d67bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='constructs__product_161f12_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='constructs__is_acti_0921dc_idx'),
        ),
    ]
