# Generated by Django 4.2 on 2026-03-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructs', '0002_remove_product_main_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
