# Generated by Django 4.2 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructs', '0003_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Порядок'),
        ),
    ]
