# Generated by Django 4.2 on 2026-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructs', '0004_alter_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('facade', 'Фасад'), ('plan', 'Планировка'), ('interior', 'Интерьер'), ('exterior', 'Екстерьер')], default='exterior', max_length=120, verbose_name='Тип изображения'),
        ),
    ]
