# Generated by Django 4.2 on 2026-04-06 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructs', '0005_productimage_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='floors_count',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='description',
        ),
        migrations.AddField(
            model_name='producttype',
            name='floor',
            field=models.DecimalField(choices=[(1.0, '1'), (1.5, '1.5'), (2.0, '2'), (3.0, '3'), (0.0, '0')], decimal_places=1, default=0.0, max_digits=2, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь, м²'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, help_text='только вид, перед этим будет добавдено название проекта и вид фотографии', max_length=120, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('facade', 'Фасад'), ('plan', 'Планировка'), ('interior', 'Интерьер'), ('exterior', 'Екстерьер')], default='exterior', max_length=20, verbose_name='Тип изображения'),
        ),
    ]
