# Generated by Django 4.2 on 2026-06-24 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructs', '0006_remove_product_floors_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Количество лайков у проекта дома', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество просмотров проекта', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, default='строительство домов и коттеджей, дома из ThermoBlock, проекты домов ThermoBlock, строительство домов из термоблока, коттеджи из ThermoBlock, ThermoBlock строительство, монолитные стены, несъемная опалубка, термоблок', max_length=300, verbose_name='Meta Keywords'),
        ),
    ]
